name: Docker Image CI

on:
  schedule:
    - cron:  '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'LibreTranslate/LibreTranslate'
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag zhzy0077/libretranslate:latest --build-arg with_models=true

    - name: Publish the Docker image
      run: docker push zhzy0077/libretranslate:latest
